# permissions for end users to edit projectconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectconfig-editor-role
rules:
- apiGroups:
  - otterize.com
  resources:
  - projectconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otterize.com
  resources:
  - projectconfigs/status
  verbs:
  - get
