apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: http-server-test
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 353146681200.dkr.ecr.us-east-1.amazonaws.com/otterize-tools:http-server-test
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-test-external
  namespace: http-server-test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: server
  ports:
    - name: tcp
      port: 8111
      targetPort: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-test-internal
  namespace: http-server-test
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: tcp
      port: 8111
      targetPort: 8111
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: http-server-test
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-traffic
  namespace: http-server-test
spec:
  podSelector:
    matchLabels:
      app: server
  ingress:
    - ports:
        - port: 8111
  policyTypes:
    - Ingress