apiVersion: apps/v1
kind: Deployment
metadata:
  name: otterize-pod-watcher
  namespace: otterize
  labels:
    app: otterize-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otterize-watcher
  template:
    metadata:
      labels:
        app: otterize-watcher
    spec:
      serviceAccountName: otterize-watcher
      containers:
        - name: otterize-watcher
          image: 353146681200.dkr.ecr.us-east-1.amazonaws.com/otterize:watcher-0.0.6
          imagePullPolicy: Always
