apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otterize-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otterize-watcher-role
subjects:
  - kind: ServiceAccount
    name: pod-watcher
    namespace: otterize
